from flask import Flask
app = Flask(__name__)
@app.route('/')
def home(): return "✅ Service Running"

import os
import discord
from discord import File
from discord.ext import commands
import aiohttp
import re
import io
import base64
import pymongo
from pymongo.mongo_client import MongoClient
from pymongo.server_api import ServerApi

TOKEN = os.getenv("TOKEN")
MONGODB_URI = os.getenv("MONGODB_URI")

mongo_client = None
db = None
settings_col = None
logs_col = None

try:
    mongo_client = MongoClient(MONGODB_URI, server_api=ServerApi('1'))
    mongo_client.admin.command('ping')
    db = mongo_client["rblxlua_data"]
    settings_col = db["settings"]
    logs_col = db["usage_logs"]
    print("✅ MongoDB Connected Successfully")
except Exception as e:
    print(f"❌ MongoDB Error: {str(e)}")

intents = discord.Intents.default()
intents.message_content = True
bot = commands.Bot(command_prefix=".", intents=intents, help_command=None)

async def delete_cmds_only(ctx):
    if ctx.invoked_with == "cmds":
        try: await ctx.message.delete()
        except: pass

def extract_url(input_text: str) -> str:
    patterns = [r'https?://[a-zA-Z0-9\-\.]+\.[a-zA-Z]{2,}(:\d+)?(/[^\s<>"\'\)\]]*)?', r'https?://[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}(:\d+)?(/[^\s<>"\'\)\]]*)?']
    for pat in patterns:
        match = re.search(pat, input_text)
        if match: return match.group(0)
    return ""

async def fetch_content(url: str) -> tuple[bool, str, str]:
    clean_url = extract_url(url)
    if not clean_url: return False, "", "No valid URL found"
    try:
        async with aiohttp.ClientSession(timeout=aiohttp.ClientTimeout(total=25)) as session:
            headers_list = [
                {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/125.0.0.0 Safari/537.36", "Accept": "*/*"},
                {"User-Agent": "Roblox/WinInet", "Accept": "text/plain,application/lua"},
                {"User-Agent": "curl/8.4.0", "Accept": "*/*"}
            ]
            last_error = ""
            for headers in headers_list:
                try:
                    async with session.get(clean_url, headers=headers, allow_redirects=True, max_redirects=8) as resp:
                        if resp.status == 404: last_error = "❌ 404: File does not exist"; continue
                        if resp.status == 403: last_error = "❌ 403: Access blocked by host"; continue
                        if resp.status >= 400: last_error = f"❌ HTTP Error: {resp.status}"; continue
                        body = await resp.text(encoding="utf-8", errors="replace")
                        if body and len(body.strip()) > 0: return True, body, "Successfully fetched"
                except Exception as e: last_error = str(e); continue
            return False, "", last_error if last_error else "❌ Could not retrieve content"
    except Exception as e: return False, "", f"❌ Error: {str(e)[:120]}"

def identify_obfuscator(code: str) -> dict:
    found = {"name": "Unknown / Custom", "confidence": 0, "version": "", "tags": []}
    checks = [
        {"name": "Lunr Obfuscator", "pat": [r'-- This file was protected using Lunr', r'return\(function\(L,M,I', r'local L=\{[0-9,"\';A-Za-z+/=]{120,}\}'], "score": 35},
        {"name": "Luraph Obfuscator", "pat": [r'-- Generated by Luraph', r'-- Luraph', r'local _=_.+loadstring\(function'], "score": 35},
        {"name": "Prometheus Obfuscator", "pat": [r'-- This Script is Part of the Prometheus', r'Prometheus Obfuscator', r'levno-710'], "score": 30},
        {"name": "WeAreDevs Obfuscator", "pat": [r'wearedevs\.net', r'loadstring\(string\.char\(', r'local _=string\.dump'], "score": 30},
        {"name": "M1rage Obfuscator", "pat": [r'M1rage', r'M1rage Obfuscator'], "score": 25},
        {"name": "Luarmor / Booster", "pat": [r'Luarmor', r'api\.booster', r'getgenv\(\)\.SCRIPT_KEY'], "score": 25},
        {"name": "Simple XOR Obfuscator", "pat": [r'for %w+ = 1, #%w+ do.*%w+ = %w+ %^ string%.byte', r'key.*xor', r'enc.*xor'], "score": 25},
        {"name": "Base64 Only Wrapper", "pat": [r'^loadstring\(base64\.decode\(', r'^return\(function.*base64'], "score": 20},
        {"name": "String.Char Array", "pat": [r'string\.char\((\d+,){20,}\d+\)', r'loadstring\(string\.char'], "score": 20},
        {"name": "Junk / Minified", "pat": [r'^(local [a-z];){10,}$', r'^[a-z]{1,2}=[^=;]+;$'], "score": 15},
        {"name": "Standard Lua", "pat": [r'^--.*$|^local |^function ', r'print\(|game:GetService'], "score": 0}
    ]
    for c in checks:
        hits = sum(1 for p in c["pat"] if re.search(p, code, re.IGNORECASE))
        if hits > 0:
            found["confidence"] += hits * c["score"]
            if hits >= 1: found["name"] = c["name"]; found["tags"].append(c["name"])
    found["confidence"] = min(100, found["confidence"])
    if found["confidence"] < 10: found["name"] = "Standard Lua / No Obfuscation"; found["confidence"] = 100
    return found

def deep_unpack(code: str) -> dict:
    report = {
        "obfuscator": identify_obfuscator(code),
        "result": code,
        "status": "Incomplete - Could not go deeper",
        "steps": [],
        "layers_reached": 0,
        "max_layers": 8
    }
    buf = code
    for depth in range(1, report["max_layers"] + 1):
        changed = False
        try:
            m = re.search(r'base64\.decode\s*\(\s*["\']([A-Za-z0-9+/=]{20,})["\']', buf)
            if m:
                dec = base64.b64decode(m.group(1)).decode('utf-8', errors='replace')
                if len(dec) > 15 and dec != buf:
                    buf = dec; report["steps"].append(f"Layer {depth}: Decoded Base64"); changed = True
        except: pass
        try:
            m = re.search(r'string\.char\(([\d,\s]{25,})\)', buf)
            if m:
                nums = [int(x.strip()) for x in m.group(1).split(',') if x.strip().isdigit() and 0 <= int(x.strip()) <= 65535]
                dec = ''.join(chr(n) for n in nums)
                if len(dec) > 15 and dec != buf:
                    buf = dec; report["steps"].append(f"Layer {depth}: Decoded string.char array"); changed = True
        except: pass
        try:
            km = re.search(r'["\']([^"\']{4,32})["\'].*?["\']([A-Za-z0-9+/=]{24,})["\']', buf, re.DOTALL)
            if km:
                k, d = km.group(1), base64.b64decode(km.group(2)).decode('latin1')
                res = []
                for idx, ch in enumerate(d): res.append(chr(ord(ch) ^ ord(k[idx % len(k)])))
                dec = ''.join(res)
                if len(dec) > 15 and dec != buf:
                    buf = dec; report["steps"].append(f"Layer {depth}: Applied XOR decode"); changed = True
        except: pass
        try:
            m = re.search(r'loadstring\(function\(\w+\).*?return\s+["\']([A-Za-z0-9+/=]{32,})["\']', buf, re.DOTALL)
            if m:
                dec = base64.b64decode(m.group(1)).decode('utf-8', errors='replace')
                if len(dec) > 15 and dec != buf:
                    buf = dec; report["steps"].append(f"Layer {depth}: Unpacked function wrapper"); changed = True
        except: pass
        report["layers_reached"] = depth
        if not changed: break
    buf = re.sub(r'--\[\[=*\[.*?\]=*\]', '', buf, flags=re.DOTALL)
    buf = re.sub(r'--.*?$', '', buf, flags=re.MULTILINE)
    buf = buf.strip()
    report["result"] = buf
    if len(report["steps"]) > 0:
        if report["layers_reached"] >= report["max_layers"]: report["status"] = "Fully unpacked - hit max layer limit"
        elif report["obfuscator"]["confidence"] <= 40: report["status"] = "Fully unpacked"
        else: report["status"] = "Partially unpacked - advanced protection remains"
    return report

def make_result_embed(ctx, title: str, deobf: dict=None, raw: str=None):
    if deobf:
        obf = deobf["obfuscator"]
        steps = "\n".join([f"• {s}" for s in deobf["steps"]]) if deobf["steps"] else "• No unpack methods applicable"
        desc = f"""{ctx.author.mention}
**Obfuscator Detected:** `{obf['name']}`
**Confidence:** `{obf['confidence']}%`
**Status:** `{deobf['status']}`
**Layers Processed:** `{deobf['layers_reached']} / {deobf['max_layers']}`

**Processing Steps:**
{steps}
"""
        content = deobf["result"]
    elif raw:
        desc = f"{ctx.author.mention}\n**Status:** Raw source fetched successfully"
        content = raw
    else:
        emb = discord.Embed(title=title, color=0xe74c3c, description=f"{ctx.author.mention}\n❌ No usable content")
        return emb, None
    if not content or len(content) < 5:
        emb = discord.Embed(title=title, color=0xe74c3c, description=desc+"\n❌ Result empty")
        return emb, None
    size_b = content.encode('utf-8')
    size_kb = len(size_b) / 1024
    file = None
    if size_kb > 10 or len(content) > 1800:
        file = File(io.BytesIO(size_b), filename="processed_result.lua")
        desc += f"\n📦 Size: `{round(size_kb,2)} KB` → Full content sent as file"
        emb = discord.Embed(title=title, color=0x3498db, description=desc)
    else:
        prev = content[:1600] + ("\n... [end truncated]" if len(content) > 1600 else "")
        desc += f"\n📦 Size: `{round(size_kb,2)} KB`\n\n**Content Preview:**\n```lua\n{prev}\n```"
        emb = discord.Embed(title=title, color=0x2ecc71 if "Fully unpacked" in desc else 0xf39c12, description=desc)
    emb.set_footer(text=f"Requested by {ctx.author}")
    return emb, file

def scan_envlog(code: str) -> dict:
    findings = {"risks": [], "severity": "Safe", "count": 0}
    patterns = {
        "Galactic / Env Logger": r'galactic|env.?log|dump.?script|extract.?source',
        "Bytecode Extraction": r'string\.dump\(',
        "Function Hooking": r'hookfunction|newcclosure|hookmetamethod|sethook',
        "File Operations": r'writefile|readfile|makefolder|listfiles|delfile',
        "Data Exfiltration": r'HttpPost|discord\.com/api/webhook|pastebin|catbox|transfer',
        "Debug Interception": r'debug\.getupvalue|debug\.getlocal|debug\.getregistry|getfenv'
    }
    for name, pat in patterns.items():
        if re.search(pat, code, re.IGNORECASE): findings["risks"].append(f"⚠️ {name}"); findings["count"] +=1
    if findings["count"] >=3: findings["severity"] = "High Risk"
    elif findings["count"] >=1: findings["severity"] = "Low Risk"
    return findings

@bot.event
async def on_ready():
    print(f"✅ Logged in as: {bot.user}")
    if db: print(f"✅ Database Ready: {db.name}")

@bot.group(name="db", invoke_without_command=True)
async def db_group(ctx):
    await delete_cmds_only(ctx)
    emb = discord.Embed(title="Database Commands", color=0x2b2d31, description=f"Hey {ctx.author.mention}\nUse these sub-commands:")
    emb.add_field(name="`db status`", value="Check database connection", inline=False)
    emb.add_field(name="`db clear`", value="Clear stored data", inline=False)
    await ctx.send(embed=emb)

@db_group.command(name="status")
async def db_status(ctx):
    await delete_cmds_only(ctx)
    emb = discord.Embed(title="Database Status", color=0x2ecc71 if db else 0xe74c3c, description=f"✅ {ctx.author.mention}\nConnected" if db else f"❌ {ctx.author.mention}\nNot available")
    await ctx.send(embed=emb)

@db_group.command(name="clear")
@commands.is_owner()
async def db_clear(ctx):
    await delete_cmds_only(ctx)
    if settings_col and logs_col: settings_col.delete_many({}); logs_col.delete_many({})
    emb = discord.Embed(title="Database Status", color=0x2ecc71, description=f"✅ {ctx.author.mention}\nAll data cleared")
    await ctx.send(embed=emb)

@bot.command(name="cmds")
async def show_commands(ctx):
    await delete_cmds_only(ctx)
    emb = discord.Embed(title="RblXLua Tool Commands", color=0x9b59b6, description=f"Hello {ctx.author.mention}\nCommands:")
    emb.add_field(name="`.l <link/loadstring>`", value="Deep unpack + exact obfuscator ID", inline=False)
    emb.add_field(name="`.get <link/loadstring>`", value="Raw source", inline=False)
    emb.add_field(name="`.env <link/loadstring>`", value="Anti-log scan", inline=False)
    emb.set_footer(text="Detects Lunr/Luraph/Prometheus/WeAreDevs/XOR and more")
    await ctx.send(embed=emb)

@bot.command(name="l")
async def deobf_command(ctx, *, link=None):
    await delete_cmds_only(ctx)
    if not link:
        emb = discord.Embed(title="⚠️ Missing Link", color=0xf39c12, description=f"{ctx.author.mention}\nExample: `.l https://pastefy.app/JJ4l7ZnB/raw`")
        return await ctx.reply(embed=emb, mention_author=True)
    proc = await ctx.reply(f"🔍 Analyzing & unpacking {ctx.author.mention}...", mention_author=True)
    ok, cont, msg = await fetch_content(link)
    if not ok:
        await proc.delete()
        return await ctx.reply(embed=discord.Embed(title="❌ Fetch Failed", color=0xe74c3c, description=f"{ctx.author.mention}\n{msg}"), mention_author=True)
    report = deep_unpack(cont)
    emb, file = make_result_embed(ctx, "🔓 Deobfuscation Result", deobf=report)
    await proc.delete()
    if file: await ctx.reply(embed=emb, file=file, mention_author=True)
    else: await ctx.reply(embed=emb, mention_author=True)
    if logs_col: logs_col.insert_one({"uid": ctx.author.id, "act": "deobf", "obf": report["obfuscator"]["name"], "url": extract_url(link), "at": discord.utils.utcnow()})

@bot.command(name="get")
async def fetch_command(ctx, *, link=None):
    await delete_cmds_only(ctx)
    if not link:
        emb = discord.Embed(title="⚠️ Missing Link", color=0xf39c12, description=f"{ctx.author.mention}\nExample: `.get https://example.com/script.lua`")
        return await ctx.reply(embed=emb, mention_author=True)
    proc = await ctx.reply(f"📄 Fetching source {ctx.author.mention}...", mention_author=True)
    ok, cont, msg = await fetch_content(link)
    if not ok:
        await proc.delete()
        return await ctx.reply(embed=discord.Embed(title="❌ Fetch Failed", color=0xe74c3c, description=f"{ctx.author.mention}\n{msg}"), mention_author=True)
    emb, file = make_result_embed(ctx, "📄 Raw Source Code", raw=cont)
    await proc.delete()
    if file: await ctx.reply(embed=emb, file=file, mention_author=True)
    else: await ctx.reply(embed=emb, mention_author=True)
    if logs_col: logs_col.insert_one({"uid": ctx.author.id, "act": "fetch", "url": extract_url(link), "at": discord.utils.utcnow()})

@bot.command(name="env")
async def envlog_command(ctx, *, link=None):
    await delete_cmds_only(ctx)
    if not link:
        emb = discord.Embed(title="⚠️ Missing Link", color=0xf39c12, description=f"{ctx.author.mention}\nExample: `.env https://example.com/script.lua`")
        return await ctx.reply(embed=emb, mention_author=True)
    proc = await ctx.reply(f"🛡️ Running scan {ctx.author.mention}...", mention_author=True)
    ok, cont, msg = await fetch_content(link)
    if not ok:
        await proc.delete()
        return await ctx.reply(embed=discord.Embed(title="❌ Fetch Failed", color=0xe74c3c, description=f"{ctx.author.mention}\n{msg}"), mention_author=True)
    scan = scan_envlog(cont)
    await proc.delete()
    emb = discord.Embed(title="🛡️ Environment Scan Report", color=0xe67e22, description=f"{ctx.author.mention}\n**Severity:** `{scan['severity']}`\n**Risks Found:** `{scan['count']}`\n")
    if scan["risks"]:
        for r in scan["risks"]: emb.add_field(name=r, value="— Detected", inline=False)
    else: emb.description += "\n✅ No env loggers or dumpers detected"
    await ctx.reply(embed=emb, mention_author=True)
    if logs_col: logs_col.insert_one({"uid": ctx.author.id, "act": "envscan", "url": extract_url(link), "at": discord.utils.utcnow()})

if __name__ == "__main__":
    from threading import Thread
    def run_flask(): app.run(host="0.0.0.0", port=10000)
    Thread(target=run_flask, daemon=True).start()
    bot.run(TOKEN)
