from flask import Flask
app = Flask(__name__)
@app.route('/')
def home(): return "✅ Service Running"

import os
import discord
from discord import File
from discord.ext import commands
import aiohttp
import re
import io
import base64
import pymongo
from pymongo.mongo_client import MongoClient
from pymongo.server_api import ServerApi

TOKEN = os.getenv("TOKEN")
MONGODB_URI = os.getenv("MONGODB_URI")

mongo_client = None
db = None
settings_col = None
logs_col = None

try:
    mongo_client = MongoClient(MONGODB_URI, server_api=ServerApi('1'))
    mongo_client.admin.command('ping')
    db = mongo_client["rblxlua_data"]
    settings_col = db["settings"]
    logs_col = db["usage_logs"]
    print("✅ MongoDB Connected Successfully")
except Exception as e:
    print(f"❌ MongoDB Error: {str(e)}")

intents = discord.Intents.default()
intents.message_content = True
bot = commands.Bot(command_prefix=".", intents=intents, help_command=None)

async def delete_cmds_only(ctx):
    if ctx.invoked_with == "cmds":
        try: await ctx.message.delete()
        except: pass

def extract_url(input_text: str) -> str:
    patterns = [r'https?://[a-zA-Z0-9\-\.]+\.[a-zA-Z]{2,}(:\d+)?(/[^\s<>"\'\)\]]*)?', r'https?://[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}(:\d+)?(/[^\s<>"\'\)\]]*)?']
    for pat in patterns:
        match = re.search(pat, input_text)
        if match: return match.group(0)
    return ""

async def fetch_content(url: str) -> tuple[bool, str, str]:
    clean_url = extract_url(url)
    if not clean_url: return False, "", "No valid URL found"
    try:
        async with aiohttp.ClientSession(timeout=aiohttp.ClientTimeout(total=20)) as session:
            headers_list = [
                {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/125.0.0.0 Safari/537.36", "Accept": "*/*"},
                {"User-Agent": "Roblox/1.0 (+https://www.roblox.com)", "Accept": "text/plain"},
                {"User-Agent": "curl/8.0.1", "Accept": "*/*"}
            ]
            last_error = ""
            for headers in headers_list:
                try:
                    async with session.get(clean_url, headers=headers, allow_redirects=True, max_redirects=5) as resp:
                        if resp.status == 404: last_error = "❌ 404: File does not exist"; continue
                        if resp.status == 403: last_error = "❌ 403: Access blocked"; continue
                        if resp.status >= 400: last_error = f"❌ Status {resp.status}"; continue
                        body = await resp.text(encoding="utf-8", errors="replace")
                        if body and len(body.strip()) > 0: return True, body, "Success"
                except Exception as e: last_error = str(e); continue
            return False, "", last_error if last_error else "❌ Could not fetch"
    except Exception as e: return False, "", f"❌ Error: {str(e)[:100]}"

def detect_protections(code: str) -> dict:
    info = {"types": [], "confidence": 0, "inner_found": False, "inner_data": ""}
    sigs = {
        "Base64 Wrapper": [r'base64\.decode\s*\(', r'["\']([A-Za-z0-9+/=]{64,})["\']'],
        "Simple XOR": [r'\^\s*string\.byte', r'key\s*=\s*["\'][^"\']{4,}["\'].*for.*len'],
        "String.Char Encoding": [r'string\.char\(([\d,\s]{30,})\)', r'loadstring\(string\.char'],
        "Lunr Obfuscator": [r'Lunr|lunr.*obfuscator|return\(function\(L,M,I', r'local L=\{[0-9,"\';A-Za-z+/=]{80,}\}'],
        "Luraph": [r'Luraph|luraph|-- This Script is Part of the Prometheus', r'-- Generated by Luraph'],
        "Prometheus": [r'Prometheus|prometheus.*obfuscator|levno-710', r'-- This Script is Part of the Prometheus'],
        "WeAreDevs": [r'wearedevs\.net/scripts', r'loadstring\(game:HttpGet\("https://wearedevs'],
        "Junk / Minified": [r'(local \w=\w;){8,}', r'([a-z]{1,2}\s*=[^=;]+[;]\s*){15,}'],
        "Nested Loadstring": [r'loadstring\s*\(.*loadstring', r'game:HttpGet.*game:HttpGet'],
        "Bytecode / String.Dump": [r'string\.dump\(loadstring', r'tostring\(loadstring']
    }
    for name, pats in sigs.items():
        hits = 0
        for p in pats:
            if re.search(p, code, re.IGNORECASE): hits +=1
        if hits > 0: info["types"].append(f"• {name}"); info["confidence"] += hits
    info["confidence"] = min(100, info["confidence"] * 15)
    inner_m = re.search(r'(loadstring\s*\(\s*)?base64\.decode\s*\(\s*["\']([A-Za-z0-9+/=]{32,})["\']', code)
    if inner_m: info["inner_found"] = True; info["inner_data"] = inner_m.group(2)
    if not info["types"]: info["types"].append("• Standard Lua / No known obfuscation detected")
    return info

def deep_deobfuscate(code: str) -> dict:
    report = {
        "original_size": len(code),
        "result": code,
        "status": "Could not fully unpack",
        "protections": detect_protections(code),
        "steps_done": []
    }
    work = code
    for _ in range(4):
        changed = False
        try:
            m = re.search(r'base64\.decode\s*\(\s*["\']([A-Za-z0-9+/=]{32,})["\']', work)
            if m:
                decoded = base64.b64decode(m.group(1)).decode('utf-8', errors='replace')
                if len(decoded) > 20 and decoded != work:
                    work = decoded
                    report["steps_done"].append("Extracted Base64 content")
                    changed = True
        except: pass
        try:
            nums = re.search(r'string\.char\(([\d,\s]{30,})\)', work)
            if nums:
                vals = [int(x.strip()) for x in nums.group(1).split(',') if x.strip().isdigit()]
                decoded = ''.join(chr(n) for n in vals if 32 <= n <= 126 or n in [9,10,13])
                if len(decoded) > 20 and decoded != work:
                    work = decoded
                    report["steps_done"].append("Decoded string.char array")
                    changed = True
        except: pass
        try:
            km = re.search(r'local \w+\s*=\s*["\']([^"\']{4,})["\'].*local \w+\s*=\s*["\']([A-Za-z0-9+/=]{32,})["\']', work, re.DOTALL)
            if km:
                key = km.group(1)
                data = base64.b64decode(km.group(2)).decode('latin1')
                res = []
                for i,c in enumerate(data): res.append(chr(ord(c) ^ ord(key[i % len(key)])))
                decoded = ''.join(res)
                if len(decoded) > 20 and decoded != work:
                    work = decoded
                    report["steps_done"].append("Applied XOR decode")
                    changed = True
        except: pass
        if not changed: break
    work = re.sub(r'--\[\[=*\[.*?\]=*\]', '', work, flags=re.DOTALL)
    work = re.sub(r'--.*?$', '', work, flags=re.MULTILINE)
    report["result"] = work.strip()
    if len(report["steps_done"]) > 0: report["status"] = "Partially unpacked" if report["protections"]["confidence"] > 60 else "Successfully unpacked"
    return report

def make_result_embed(ctx, title: str, content: str, deobf_report: dict=None):
    if not content or len(content.strip()) < 3:
        emb = discord.Embed(title=title, color=0xe74c3c, description=f"{ctx.author.mention}\n❌ No usable content found")
        return emb, None
    if deobf_report:
        prot_text = "\n".join(deobf_report["protections"]["types"])
        steps_text = "\n".join([f"• {s}" for s in deobf_report["steps_done"]]) if deobf_report["steps_done"] else "• No unpack steps could be applied"
        desc = f"{ctx.author.mention}\n**Status:** `{deobf_report['status']}`\n**Protection Confidence:** `{deobf_report['protections']['confidence']}%`\n\n**Detected Protections:**\n{prot_text}\n\n**Processing Steps:**\n{steps_text}\n"
        show_content = deobf_report["result"]
    else:
        desc = f"{ctx.author.mention}\n**Status:** Fetched successfully\n"
        show_content = content
    content_bytes = show_content.encode('utf-8')
    size_kb = len(content_bytes) / 1024
    file = None
    if size_kb > 10 or len(show_content) > 1900:
        file = File(io.BytesIO(content_bytes), filename="processed_result.lua")
        desc += f"\n📦 Size: `{round(size_kb,2)} KB` → Sent as file to preserve full content"
        emb = discord.Embed(title=title, color=0x3498db, description=desc)
    else:
        preview = show_content[:1500] + ("\n... (truncated)" if len(show_content) > 1500 else "")
        desc += f"\n📦 Size: `{round(size_kb,2)} KB`\n\n**Content Preview:**\n```lua\n{preview}\n```"
        emb = discord.Embed(title=title, color=0x2ecc71 if deobf_report and "Successfully" in deobf_report["status"] else 0xf39c12, description=desc)
    emb.set_footer(text=f"Requested by {ctx.author}")
    return emb, file

def scan_envlog(code: str) -> dict:
    findings = {"risks": [], "severity": "Safe", "count": 0}
    patterns = {
        "Galactic / Env Logger": r'galactic|env.?log|dump.?script|extract.?source',
        "Bytecode Extraction": r'string\.dump\(',
        "Function Hooking": r'hookfunction|newcclosure|hookmetamethod|sethook',
        "File Operations": r'writefile|readfile|makefolder|listfiles|delfile',
        "Data Exfiltration": r'HttpPost|discord\.com/api/webhook|pastebin\.com|catbox\.moe',
        "Debug Interception": r'debug\.getupvalue|debug\.getlocal|debug\.getregistry|getfenv'
    }
    for name, pat in patterns.items():
        if re.search(pat, code, re.IGNORECASE): findings["risks"].append(f"⚠️ {name}"); findings["count"] +=1
    if findings["count"] >=3: findings["severity"] = "High Risk"
    elif findings["count"] >=1: findings["severity"] = "Low Risk"
    return findings

@bot.event
async def on_ready():
    print(f"✅ Logged in as: {bot.user}")
    if db: print(f"✅ Database Ready: {db.name}")

@bot.group(name="db", invoke_without_command=True)
async def db_group(ctx):
    await delete_cmds_only(ctx)
    emb = discord.Embed(title="Database Commands", color=0x2b2d31, description=f"Hey {ctx.author.mention}\nUse these sub-commands:")
    emb.add_field(name="`db status`", value="Check database connection", inline=False)
    emb.add_field(name="`db clear`", value="Clear stored data (owner only)", inline=False)
    await ctx.send(embed=emb)

@db_group.command(name="status")
async def db_status(ctx):
    await delete_cmds_only(ctx)
    emb = discord.Embed(title="Database Status", color=0x2ecc71 if db else 0xe74c3c, description=f"✅ {ctx.author.mention}\nMongoDB connected" if db else f"❌ {ctx.author.mention}\nDatabase unavailable")
    await ctx.send(embed=emb)

@db_group.command(name="clear")
@commands.is_owner()
async def db_clear(ctx):
    await delete_cmds_only(ctx)
    if settings_col and logs_col: settings_col.delete_many({}); logs_col.delete_many({})
    emb = discord.Embed(title="Database Status", color=0x2ecc71, description=f"✅ {ctx.author.mention}\nAll data cleared")
    await ctx.send(embed=emb)

@bot.command(name="cmds")
async def show_commands(ctx):
    await delete_cmds_only(ctx)
    emb = discord.Embed(title="RblXLua Tool Commands", color=0x9b59b6, description=f"Hello {ctx.author.mention}\nCommands:")
    emb.add_field(name="`.l <link/loadstring>`", value="Deep unpack + protection detection", inline=False)
    emb.add_field(name="`.get <link/loadstring>`", value="Raw full source", inline=False)
    emb.add_field(name="`.env <link/loadstring>`", value="Anti-log deep scan", inline=False)
    emb.set_footer(text="Works with Pastefy, Pastebin, GitHub, Render, Netlify etc.")
    await ctx.send(embed=emb)

@bot.command(name="l")
async def deobf_command(ctx, *, link=None):
    await delete_cmds_only(ctx)
    if not link:
        emb = discord.Embed(title="⚠️ Missing Link", color=0xf39c12, description=f"{ctx.author.mention}\nExample: `.l https://pastefy.app/JJ4l7ZnB/raw`")
        return await ctx.reply(embed=emb, mention_author=True)
    processing = await ctx.reply(f"🔍 Analyzing & unpacking {ctx.author.mention}...", mention_author=True)
    ok, content, msg = await fetch_content(link)
    if not ok:
        await processing.delete()
        return await ctx.reply(embed=discord.Embed(title="❌ Fetch Failed", color=0xe74c3c, description=f"{ctx.author.mention}\n{msg}"), mention_author=True)
    report = deep_deobfuscate(content)
    emb, file = make_result_embed(ctx, "🔓 Deobfuscation Result", report["result"], report)
    await processing.delete()
    if file: await ctx.reply(embed=emb, file=file, mention_author=True)
    else: await ctx.reply(embed=emb, mention_author=True)
    if logs_col: logs_col.insert_one({"uid": ctx.author.id, "act": "deobf", "url": extract_url(link), "at": discord.utils.utcnow()})

@bot.command(name="get")
async def fetch_command(ctx, *, link=None):
    await delete_cmds_only(ctx)
    if not link:
        emb = discord.Embed(title="⚠️ Missing Link", color=0xf39c12, description=f"{ctx.author.mentionion}\nExample: `.get https://example.com/file.lua`")
        return await ctx.reply(embed=emb, mention_author=True)
    processing = await ctx.reply(f"📄 Fetching source {ctx.author.mention}...", mention_author=True)
    ok, content, msg = await fetch_content(link)
    if not ok:
        await processing.delete()
        return await ctx.reply(embed=discord.Embed(title="❌ Fetch Failed", color=0xe74c3c, description=f"{ctx.author.mention}\n{msg}"), mention_author=True)
    emb, file = make_result_embed(ctx, "📄 Raw Source Code", content)
    await processing.delete()
    if file: await ctx.reply(embed=emb, file=file, mention_author=True)
    else: await ctx.reply(embed=emb, mention_author=True)
    if logs_col: logs_col.insert_one({"uid": ctx.author.id, "act": "fetch", "url": extract_url(link), "at": discord.utils.utcnow()})

@bot.command(name="env")
async def envlog_command(ctx, *, link=None):
    await delete_cmds_only(ctx)
    if not link:
        emb = discord.Embed(title="⚠️ Missing Link", color=0xf39c12, description=f"{ctx.author.mention}\nExample: `.env https://example.com/script.lua`")
        return await ctx.reply(embed=emb, mention_author=True)
    processing = await ctx.reply(f"🛡️ Running deep scan {ctx.author.mention}...", mention_author=True)
    ok, content, msg = await fetch_content(link)
    if not ok:
        await processing.delete()
        return await ctx.reply(embed=emb, mention_author=True)
    scan = scan_envlog(content)
    await processing.delete()
    emb = discord.Embed(title="🛡️ Environment Scan Report", color=0xe67e22, description=f"{ctx.author.mention}\n**Severity:** `{scan['severity']}`\n**Total Risks:** `{scan['count']}`\n")
    if scan["risks"]:
        for r in scan["risks"]: emb.add_field(name=r, value="— Detected", inline=False)
    else: emb.description += "\n✅ No env loggers or dumpers found"
    await ctx.reply(embed=emb, mention_author=True)
    if logs_col: logs_col.insert_one({"uid": ctx.author.id, "act": "envscan", "url": extract_url(link), "at": discord.utils.utcnow()})

if __name__ == "__main__":
    from threading import Thread
    def run_flask(): app.run(host="0.0.0.0", port=10000)
    Thread(target=run_flask, daemon=True).start()
    bot.run(TOKEN)
